import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Product Details",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavBar></NavBar>
				{children}
				<div className="bg-slate-800 p-2">
					<p className="text-center  text-white text-sm my-3">
						Copyright © 2023{" "}
						<Link
							target="_blank"
							className="underline text-amber-400 font-medium"
							href="https://muhaiminul101.vercel.app/"
						>
							Md Muhaiminul
						</Link>
						. All rights reserved.
					</p>
				</div>
			</body>
		</html>
	);
}
